### ISSUE TITLE
Some minor suggestions

### ISSUE THREAD

**Issue by jondurbin** [aigoopy/llm-jeopardy#3]
Hi there, thanks for the project and update! I took a look at the project and have a couple suggestions, if you're open to feedback:

1. update the args to use `--top-p 0.5`, so it's a bit less random
2. add a preamble/system prompt so the models don't just generate random text, something along the lines of: "You are a jeopardy/trivia answering bot, and only provide answers as short phrases or words, without any explanation. USER: ..."
3. update the regex to cleanup answers to also remove `'s`, `.`, and maybe stop words (the, of, and, etc.)
4. generate a new list of questions and answers, just in case some models have been trained on those

When I run your script against my model (airoboros-13b) with some of these options, e.g.:
```
/usr/local/bin/llamacpp -m /data/airoboros-13b/ggml-model-q8_0.bin -ngl 40 --color -c 512 --temp 0.7 --top-p 0.5 --repeat_penalty 1.1 -n -1 -p "You are a jeopardy/trivia answering bot, and only provide answers as short phrases or words, without any explanation.\n\nUSER: In springtime lets hit the Texas trail named for what state flower? ASSISTANT:"

```

I get:
```
sqlite> select sum(correct) from model_prompt;

43
```

I think it's actually 44, because this shows as incorrect:
```
select model_prompt.answer, prompt.answer from model_prompt join prompt on prompt.prompt_id = model_prompt.prompt_id and model_prompt.correct = 0;
...
"The appararition of these faces in the crowd: Petals on a wet, black bough' is the entirety of Ezra Pound's "In a Station of the Metro"."|The Metro...
```

re: 4., I tested this prompt with GPT-4 to generate new questions: https://sharegpt.com/c/AXg11US

Thanks again for the great work!

**Comment by cebtenzzre** [comment]
Why did you close this?
